substitutions:
  name: "livingroom-enviro"
  friendly_name: Livingroom Enviro
#---------------------------------------------------------------------------------------------------
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
#---------------------------------------------------------------------------------------------------
esp32:
  board: esp32dev
  framework:
    type: arduino
#---------------------------------------------------------------------------------------------------
# Enable logging
logger:
    baud_rate: 0
#---------------------------------------------------------------------------------------------------
# Enable Home Assistant API
api:
  encryption: 
    key: !secret haapi_key
#---------------------------------------------------------------------------------------------------
ota:
  - platform: esphome
    password: !secret ota_password
#---------------------------------------------------------------------------------------------------
# Creates a simple web server on the node that can be accessed through any browser
#web_server:
#  port: 80
#  ota: false
#  auth:
#    username: admin
#    password: !secret web_password
#---------------------------------------------------------------------------------------------------
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  fast_connect: off
#---------------------------------------------------------------------------------------------------
switch:
  - platform: restart
    name: "${friendly_name} Restart"
#---------------------------------------------------------------------------------------------------
time:
  - platform: homeassistant
    id: esptime
#---------------------------------------------------------------------------------------------------
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
      update_interval: 1h
    ssid:
      name: ${friendly_name} SSID
      update_interval: 1h
    mac_address:
      name: ${friendly_name} Mac
#---------------------------------------------------------------------------------------------------
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
#---------------------------------------------------------------------------------------------------
i2c:
  - id: bus_a
    sda: 21
    scl: 22
#---------------------------------------------------------------------------------------------------
sensor:
  - platform: wifi_signal
    name: "${friendly_name} Signal Strength"
    update_interval: 60s
#--------------------------------------
  - platform: sds011
    update_interval: 0min
    pm_2_5:
      name: "${friendly_name} PM <2.5µm"
      id: LRPM25
    pm_10_0:
      name: "${friendly_name} PM <10.0µm"
      id: LRPM100
#--------------------------------------
  - platform: scd30
    i2c_id: bus_a
    co2:
      name: "${friendly_name} scd30_CO2"
      accuracy_decimals: 1
    temperature:
      name: "${friendly_name} scd30_Temperature"
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} scd30_Humidity"
      accuracy_decimals: 1
    temperature_offset: 1.5 °C
    altitude_compensation: 1945m
    automatic_self_calibration: false
    address: 0x61
    update_interval: 60s
#---------------------------------------------------------------------------------------------------
# Example on how to implement a UI section in HA for manual calibration.
# Note: Please enter first a CO2 value before pressing the button.
button:
  - platform: template
    name: "${friendly_name} SCD30 Manual Cal"
    entity_category: "config"
    on_press:
      then:
        - scd30.force_recalibration_with_reference:
            value: !lambda 'return id(co2_cal).state;'
#---------------------------------------------------------------------------------------------------
number:
  - platform: template
    name: "${friendly_name} CO2 Cal Value"
    optimistic: true
    min_value: 350
    max_value: 4500
    step: 1
    id: co2_cal
    icon: "mdi:molecule-co2"
    entity_category: "config"